### ISSUE TITLE
Input uses US keyboard layout

### ISSUE THREAD

**Issue by clawoflight** [marczuo/grc-beta-code#1]
This may be a configuration issue on my part, in which case it would be awesome if you could help me find a solution on my end.

Input works, but the underlying characters are from the en_us layout even though I use a german keyboard. Examples:
y -> ζ
z -> ψ
( -> *
+ -> ]

and so on.

Do you know what I can do about that, or is this a problem on your end?

**Comment by marczuo** [comment]
Try ibus preferences - Advanced - Use system keyboard layout.

Personally I prefer _not_ using the actual keyboard layout (I have fr azerty), because for some reason m17n doesn't work well with AltGr combinations and thus I cannot use | (AltGr+-) to type the iota subscript. It didn't take me too long to get used to the en_US layout.

**Comment by clawoflight** [comment]
Ah, un Français :) 

J'ai essayé d'utiliser "use system keyboard layout", mais ça semble utiliser un clavier Américain, parce que mon clavier allemand arrète de fonctionner après...

Bref, je vais devoir apprendre le clavier Américain.
Merci quand même, et merci pour ce projet :)

**Comment by marczuo** [comment]
Oui, ça me paraît la meilleure solution pour l'instant.

Si l'option d'utiliser la disposition clavier système ne fonctionne pas, il faut éventuellement lancer `setxkbmap de` dans le shell, mais comme je l'ai dit, les combinaisons AltGr ne marcheraient pas pour taper les diacritiques.
